site:
  title: "Product Enablement: AAP 2.7 Fundamentals and Deployment"
  start_page: AAP-2.7-Fundamentals-and-Deployment::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
